// Generated by CoffeeScript 1.8.0
  var Cal;

  Cal = (function() {
    function Cal() {
      this.value = 2;
    }

    Cal.prototype.add = function(a, b) {
      return a + b;
    };

    Cal.prototype.subtract = function(a, b) {
      return a - b;
    };

    Cal.prototype.addValue = function(a) {
      return this.value + a;
    };

    return Cal;

  })();

